repeat = 10

[[experiment]]
thread_count = [1, 2, 4, 8, 16, 24, 32]
# process_count = [10]
allocator = [{ name = "cxlalloc" }]
# allocator = [{ name = "mimalloc" }]

[experiment.allocator_config]
numa = [{ policy = "bind", node = 0 }, { policy = "bind", node = 2 }]
size = [0, 68719476736]

[[experiment.benchmark]]
kind = "thread_test"
iteration_count = [9600]
operation_count = [10000]
object_size = [8, 32768]

[[experiment.benchmark]]
kind = "xmalloc"
operation_count = [960000]

[[experiment.benchmark]]
kind = "key_value"

[[experiment.benchmark.workload]]
name = "ycsb"
record_count = [960000]
operation_count = [960000]

[[experiment.benchmark.workload.mix]]
phase = "load"

[[experiment.benchmark.workload.mix]]
phase = "run"
read = 0.50
insert = 0.25
delete = 0.25
distribution = "zipfian"

[[experiment.benchmark.workload.mix]]
phase = "run"
read = 0.95
insert = 0.05
distribution = "latest"

[[experiment.benchmark.workload]]
name = "memcached"
operation_count = [960000]
trace = [
    "twitter/cluster12.000.parquet",
    "twitter/cluster15.000.parquet",
    "twitter/cluster31.000.parquet",
]

[[experiment.benchmark.workload]]
name = "memcached"
operation_count = [960000]
trace = ["twitter/cluster37.000.parquet"]
